//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actualizator {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Actualizator.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Acceso denegado a la ruta especificada!.
        /// </summary>
        internal static string accessDenied {
            get {
                return ResourceManager.GetString("accessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Guarde la configuración actual!.
        /// </summary>
        internal static string alertaGuardarProyecto {
            get {
                return ResourceManager.GetString("alertaGuardarProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a log.txt.
        /// </summary>
        internal static string archivoLog {
            get {
                return ResourceManager.GetString("archivoLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a proyectos.xml.
        /// </summary>
        internal static string archivoProyecto {
            get {
                return ResourceManager.GetString("archivoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  borrada | Fecha: .
        /// </summary>
        internal static string borrado {
            get {
                return ResourceManager.GetString("borrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        internal static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a click para expandir.
        /// </summary>
        internal static string clickExpandir {
            get {
                return ResourceManager.GetString("clickExpandir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Compruebe las rutas de las carpetas de destino!.
        /// </summary>
        internal static string comprobarDestino {
            get {
                return ResourceManager.GetString("comprobarDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Compruebe la ruta de la carpeta de origen!.
        /// </summary>
        internal static string comprobarOrigen {
            get {
                return ResourceManager.GetString("comprobarOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extrayendo información....
        /// </summary>
        internal static string extrayendoInfo {
            get {
                return ResourceManager.GetString("extrayendoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo XML guardado  | Fecha:.
        /// </summary>
        internal static string guardadoXML {
            get {
                return ResourceManager.GetString("guardadoXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup: .
        /// </summary>
        internal static string mensajeBackup {
            get {
                return ResourceManager.GetString("mensajeBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres borrar el destino?.
        /// </summary>
        internal static string mensajeBorrarDestino {
            get {
                return ResourceManager.GetString("mensajeBorrarDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro que quiere borrar la configuración?.
        /// </summary>
        internal static string mensajeBorrarProyecto {
            get {
                return ResourceManager.GetString("mensajeBorrarProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: .
        /// </summary>
        internal static string mensajeError {
            get {
                return ResourceManager.GetString("mensajeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  | Fecha: .
        /// </summary>
        internal static string mensajeFecha {
            get {
                return ResourceManager.GetString("mensajeFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Rellene el campo de filtro!.
        /// </summary>
        internal static string mensajeRellenarFiltro {
            get {
                return ResourceManager.GetString("mensajeRellenarFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres restaurar el útimo backup?.
        /// </summary>
        internal static string mensajeRestaurarBackup {
            get {
                return ResourceManager.GetString("mensajeRestaurarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una configuracion con el mismo nombre.
        /// </summary>
        internal static string mismoNombre {
            get {
                return ResourceManager.GetString("mismoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Introduce un ruta de destino!.
        /// </summary>
        internal static string noDestino {
            get {
                return ResourceManager.GetString("noDestino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No hay backup de la configuración seleccionada!.
        /// </summary>
        internal static string noLastBackup {
            get {
                return ResourceManager.GetString("noLastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Indique un nombre para la configuración!.
        /// </summary>
        internal static string nombreProyecto {
            get {
                return ResourceManager.GetString("nombreProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Introduce un ruta de origen.
        /// </summary>
        internal static string noOrigen {
            get {
                return ResourceManager.GetString("noOrigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva configuracion.
        /// </summary>
        internal static string nuevoProyecto {
            get {
                return ResourceManager.GetString("nuevoProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        internal static string proyecto {
            get {
                return ResourceManager.GetString("proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar.
        /// </summary>
        internal static string restaurar {
            get {
                return ResourceManager.GetString("restaurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Backup restaurado  | Fecha:.
        /// </summary>
        internal static string restaurarBackup {
            get {
                return ResourceManager.GetString("restaurarBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string saludo {
            get {
                return ResourceManager.GetString("saludo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpetas sincronizadas | Fecha:.
        /// </summary>
        internal static string sincronizarCarpetas {
            get {
                return ResourceManager.GetString("sincronizarCarpetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Archivo XML corrupto!.
        /// </summary>
        internal static string xmlCorrupto {
            get {
                return ResourceManager.GetString("xmlCorrupto", resourceCulture);
            }
        }
    }
}
